name: Reusable workflow to run trivy scan

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      scan-type:
        required: true
        type: string
      format:
        required: true
        type: string
      output:
        required: false
        type: string
        default: trivy.sarif
      image-ref:
        required: false
        type: string
        default: ""
      severity:
        required: false
        type: string
        default: "CRITICAL,HIGH"
      exit-code:
        required: true
        type: number
      publish:
        required: true
        type: boolean

jobs:
  trivy-scan:
    name: Trivy - ${{ inputs.runs-on }} - ${{ inputs.scan-type }} ${{ inputs.image-ref }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.8.0
        with:
          scan-type: ${{ inputs.scan-type }}
          image-ref: ${{ inputs.image-ref }}
          ignore-unfixed: false
          format: ${{ inputs.format }}
          output: ${{ inputs.output }}
          exit-code: ${{ inputs.exit-code }}
          severity: ${{ inputs.severity }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b8d3b6e8af63cde30bdc382c0bc28114f4346c88 # v2.28.1
        if: ${{ inputs.publish }}
        with:
          sarif_file: ${{ inputs.output }}
